services:
  - type: web
    name: perpustakaan-laravel
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT